version: "0.2"
ignorePaths:
  - "**/*.rive.dart"
dictionaryDefinitions: []
dictionaries: []
words:
  - antialiasing
  - Artboard
  - artboards
  - autoplay
  - cupertino
  - kuhnroyal
  - posix
  - pubspec
  - subosito
ignoreWords: []
import: []
