name: rive_parser
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=2.18.1 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  path: ^1.8.2
  rive: ^0.9.1
