name: rive_generator
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.2 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  logging: ^1.1.0
  path: ^1.8.2
  rive: ^0.9.1
  yaml: ^3.1.1
