name: rive_generator
description: Command line application to generate code from rive files.
version: 0.1.0
repository: https://github.com/ronba/rive-tools/tree/main/packages/rive_generator
homepage: https://github.com/ronba/rive-tools

environment:
  sdk: ">=2.18.2 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  logging: ^1.1.0
  path: ^1.8.2
  rive: ^0.9.1
  yaml: ^3.1.1
